# SPDX-FileCopyrightText: Copyright 2025 Stacklok, Inc.
# SPDX-License-Identifier: Apache-2.0

# Rust toolchain flavour image for apiary.
# Adds rustc and cargo on top of the base image.
FROM ghcr.io/stacklok/apiary/base:latest

RUN apk add --no-cache \
    rust \
    cargo \
    make
