# SPDX-FileCopyrightText: Copyright 2025 Stacklok, Inc.
# SPDX-License-Identifier: Apache-2.0

# Rust toolchain flavour image for Brood Box.
# Adds Rust toolchain (rustc + cargo) on top of the base image.
FROM ghcr.io/stacklok/brood-box/base:latest

RUN apk add --no-cache \
    rust \
    make
