# SPDX-FileCopyrightText: Copyright 2025 Stacklok, Inc.
# SPDX-License-Identifier: Apache-2.0

# Node.js toolchain flavour image for apiary.
# Adds Node.js and npm on top of the base image.
FROM ghcr.io/stacklok/apiary/base:latest

RUN apk add --no-cache \
    nodejs \
    npm \
    make
